# Generated by Django 6.0.5 on 2026-05-11 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField()),
                ('nom_prenoms', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('numero_police', models.CharField(blank=True, max_length=50, null=True)),
                ('objet_visite', models.CharField(blank=True, max_length=200, null=True)),
                ('canal', models.CharField(choices=[('Call Center VIE', 'Call Center VIE'), ('Call Center IARD', 'Call Center IARD'), ('Espace Conseil VIE', 'Espace Conseil VIE')], max_length=30)),
                ('date_appel', models.DateField()),
                ('statut_appel', models.CharField(choices=[('Joint', 'Joint'), ('Injoignable', 'Injoignable'), ('Pas de reponse', 'Pas de reponse')], max_length=20)),
                ('nps_score', models.IntegerField(blank=True, null=True)),
                ('categorie_nps', models.CharField(blank=True, choices=[('Promoteur', 'Promoteur'), ('Passif', 'Passif'), ('Detracteur', 'Detracteur')], max_length=20)),
                ('csat', models.CharField(blank=True, choices=[('Satisfait', 'Satisfait'), ('Insatisfait', 'Insatisfait')], max_length=20)),
                ('ces', models.CharField(blank=True, choices=[('Effort faible', 'Effort faible'), ('Effort modere', 'Effort modere'), ('Effort eleve', 'Effort eleve')], max_length=20)),
                ('motif_insatisfaction', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reponse Client',
                'ordering': ['-date_appel'],
            },
        ),
    ]
