# Generated by Django 6.0.5 on 2026-05-28 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=50)),
                ('nouvelle_valeur', models.TextField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvee', 'Approuvee'), ('Rejetee', 'Rejetee')], default='En attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saisie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation_client.reponseclient')),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'ordering': ['-date_demande'],
            },
        ),
    ]
