# Generated by Django 6.0.5 on 2026-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_client', '0002_demandemodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseclient',
            name='sous_canal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
