# Generated by Django 6.0.5 on 2026-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_client', '0003_reponseclient_sous_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponseclient',
            name='sous_canal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
